### ISSUE TITLE
Packaging "php" extension fails in Maven3

### ISSUE THREAD

**Issue by sarnowski** [php-maven/maven-php-plugin#1]
When using the plugin's extension for php packaging, maven-3.0-beta2 fails to install the resulting files into the repository. I tracked it down to the very last step in the plexus components.xml which fails.

**Comment by sarnowski** [comment]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-plugin-plugin:2.6:updateRegistry (default-updateRegistry) on project pinjector: Execution default-updateRegistry of goal org.apache.maven.plugins:maven-plugin-plugin:2.6:updateRegistry failed: Unable to load the mojo 'updateRegistry' in the plugin 'org.apache.maven.plugins:maven-plugin-plugin:2.6'. A required class is missing: org/apache/maven/plugin/registry/PluginRegistry

**Comment by marcoooo** [comment]
Hi, I found a solution, certainly not very clean neither for a long time :

I found something strange inside the file maven-php-plugin-1.1.jar in /META-INF/plexus/components.xml :
the files contains lines associated to install phase such as follow :

<install>
    org.apache.maven.plugins:maven-install-plugin:install,
    org.apache.maven.plugins:maven-plugin-plugin:updateRegistry
</install>

I removed the line concerning the org.apache.maven.plugins:maven-plugin-plugin:updateRegistry, then my install command went well after.

I know this is not a proper solution, but waiting for a real one, I suggest you to do that.

Regards

**Comment by toddpi314** [comment]
This issue is still occurring with maven 3.0.3 on OSX 10.6.7.

**Comment by mepeisen** [comment]
Please retry with php-maven 2.0-snapshot. See the google groups for instruction where to find it. Closed because the new testcases (see maven3 branch) are working with phar packaging. Please report new issues related to php-maven2 at our trac: http://trac.php-maven.org
