### ISSUE TITLE
Output of php5-web-archetype is .phar not .zip/.tar.gz

### ISSUE THREAD

**Issue by achingbrain** [php-maven/maven-php-plugin#12]
I have created a php5-web-archetype by running:

```
mvn archetype:generate \
-DarchetypeGroupId=org.phpmaven \
-DarchetypeArtifactId=php5-web-archetype \
-DarchetypeVersion=2.0-SNAPSHOT \
-DgroupId=org.sample \
-DartifactId=my-app \
-Dversion=0.0.1-SNAPSHOT
```

The documentation at http://php-maven.org/branches/2.0-SNAPSHOT/php-web-5min.html states:

```
Switch to your sample project directory

cd my-app

and run:

mvn package

The command line will print out various actions, ending with the following:

 ...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESSFUL
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6 seconds
[INFO] Finished at: Thu Jul 20 19:15:06 CDT 2008
[INFO] Final Memory: 3M/6M
[INFO] ------------------------------------------------------------------------         

Maven has created a zip and a tar package under the project's target folder.
```

Yet, when I run mvn package I am left with my-app-0.0.1-SNAPSHOT.phar in the target directory instead of a zip file.

**Comment by achingbrain** [comment]
Really sorry to open all these issues in such quick succession, by the way.  I figure better than one long rambling one.

**Comment by mepeisen** [comment]
thanks for opening them. However the phars will always be bcreated. They are the "php way". Web applications will have to generate tars and other archive types with "installable" packages via assemblies. The assemblies are still there but not yet active. They will be revived soon. Maybe for 2.0.1
I will change the documentation as soon as I do some rework on the web archetype.
