### ISSUE TITLE
Feature request: Set phar metadata entries in pom

### ISSUE THREAD

**Issue by jthomaskerr** [php-maven/maven-php-plugin#13]
I would like to be able to add metadata to a phar as part of a maven phase. This is a simple change to add an extra configuration entry to the build plugin, eg:

```
  <plugin>
    <groupId>org.phpmaven</groupId>
    <artifactId>maven-php-phar</artifactId>
    <configuration>
      <pharConfig>
        <stub>${stub}</stub>  
        <metadata>
          <readme>${readme}</readme>
        </metadata>          
      </pharConfig>
    </configuration>
  </plugin>
```

I have implemented these changes in the 2.0-SNAPSHOT branch (is this the appropriate place?) and attached a patch. it would be fantastic if this made it to the next release.

**Comment by jthomaskerr** [comment]
diff --git a/branches/2.0-SNAPSHOT/maven-php-phar/src/main/java/org/phpmaven/phar/IPharPackagingRequest.java b/branches/2.0-SNAPSHOT/maven-php-phar/src/main/java/org/phpmaven/phar/IPharPackagingRequest.java
index b0e8ec9..aefba66 100644
--- a/branches/2.0-SNAPSHOT/maven-php-phar/src/main/java/org/phpmaven/phar/IPharPackagingRequest.java
+++ b/branches/2.0-SNAPSHOT/maven-php-phar/src/main/java/org/phpmaven/phar/IPharPackagingRequest.java
@@ -17,6 +17,7 @@
 package org.phpmaven.phar;

 import java.io.File;
+import java.util.Map;

 import org.phpmaven.core.IComponentFactory;

@@ -107,6 +108,14 @@ import org.phpmaven.core.IComponentFactory;
-   php files.
-   </td>
- </tr>
  - \* <tr>
  - \*   <td>metadata</td>
  - \*   <td>-</td>
  - \*   <td>-</td>
  - \*   <td>-</td>
  - \*   <td>List of arbitrary elements that will be added to the phar metadata.<p>Usage: &lt;metadata&gt;&lt;myMetadataKey&gt;Value&lt;/myMetadataKey&gt;&lt/metadata&gt;
  - \*   </td>
  - \* </tr>
- </table>
- 
- @author Martin Eisengardt Martin.Eisengardt@googlemail.com
  @@ -323,5 +332,16 @@ public interface IPharPackagingRequest {
  - @return true to compress
    */
    boolean isCompressed();
    -   
      +
    -    /**
    -     \* Returns the phar metadata
    -     \* @return the metadata elements
    -     */
    -   Map<String, String> getMetadata();
      +
    -   /**
    -    \* Sets the phar metadata
    -    \* @param metadatas the metadata elements
    -    */
    -   void setMetadata(Map<String,String> metadatas);
      }
      diff --git a/branches/2.0-SNAPSHOT/maven-php-phar/src/main/java/org/phpmaven/phar/PharPackager.java b/branches/2.0-SNAPSHOT/maven-php-phar/src/main/java/org/phpmaven/phar/PharPackager.java
      index 43e8642..984c910 100644
      --- a/branches/2.0-SNAPSHOT/maven-php-phar/src/main/java/org/phpmaven/phar/PharPackager.java
      +++ b/branches/2.0-SNAPSHOT/maven-php-phar/src/main/java/org/phpmaven/phar/PharPackager.java
      @@ -19,6 +19,7 @@ package org.phpmaven.phar;
      import java.io.File;
      import java.util.ArrayList;
      import java.util.List;
      +import java.util.Map.Entry;
  
  import org.apache.maven.execution.MavenSession;
  import org.apache.maven.plugin.logging.Log;
  @@ -99,7 +100,16 @@ public class PharPackager implements IPharPackager {
  
  ```
   final String targetMasked = request.getTargetDirectory().getAbsolutePath().replace("\\", "\\\\");
   final String stubToUse = request.getStub().replace("\\", "\\\\").replace("'", "\\'");
  ```
  -   
    +
  -        final StringBuilder metadata = new StringBuilder();
  -        if (!request.getMetadata().isEmpty() ) {
  -           metadata.append("$metadata = $phar->getMetadata();\n");
  -           for (Entry<String, String> entry : request.getMetadata().entrySet()) {
  -               metadata.append(String.format("$metadata['%s'] = '%s';\n", entry.getKey(), entry.getValue()));
  -           }
  -           metadata.append("$phar->setMetadata($metadata);\n");
  -        }
    +
     String compression = "";
     if (request.isCompressed()) {
         if (request.isLargePhar()) {
    @@ -115,7 +125,8 @@ public class PharPackager implements IPharPackager {
             replace("$:{pharcontents}", contents.toString()).
             // TODO: May we need to set a compression template????
             replace("$:{pharcompression}", compression).
  -                replace("$:{pharstub}", "<?php " + stubToUse + " __HALT_COMPILER(); ?>");
  -                replace("$:{pharstub}", "<?php " + stubToUse + " __HALT_COMPILER(); ?>").
  - ```
               replace("$:{pharmetadata}", metadata);
    ```
    
     // XXX: respect build directory (set working path)
     exec.executeCode("", snippet);
    diff --git a/branches/2.0-SNAPSHOT/maven-php-phar/src/main/java/org/phpmaven/phar/PharPackagingRequest.java b/branches/2.0-SNAPSHOT/maven-php-phar/src/main/java/org/phpmaven/phar/PharPackagingRequest.java
    index e952a3e..06d92c1 100644
    --- a/branches/2.0-SNAPSHOT/maven-php-phar/src/main/java/org/phpmaven/phar/PharPackagingRequest.java
    +++ b/branches/2.0-SNAPSHOT/maven-php-phar/src/main/java/org/phpmaven/phar/PharPackagingRequest.java
    @@ -18,7 +18,9 @@ package org.phpmaven.phar;
  
  import java.io.File;
  import java.util.ArrayList;
  +import java.util.HashMap;
  import java.util.List;
  +import java.util.Map;
  
  import org.codehaus.plexus.component.annotations.Component;
  import org.codehaus.plexus.component.annotations.Configuration;
  @@ -55,6 +57,7 @@ public class PharPackagingRequest implements IPharPackagingRequest {
           "$:{pharcontents}" + 
           "$:{pharcompression}" + 
           "$phar->setStub('$:{pharstub}');\n" + 
  -            "$:{pharmetadata}" +
         "$phar->stopBuffering();\n")
    private String packagePhpTemplate;

@@ -120,6 +123,11 @@ public class PharPackagingRequest implements IPharPackagingRequest {
     private boolean largeFile;

```
 /**
```
-     \*  The metadata entries
-     */
-    private Map<String,String> metadata = new HashMap<String,String>();
  +
-    /**
  - {@inheritDoc}
    */
    @Override
    @@ -294,4 +302,20 @@ public class PharPackagingRequest implements IPharPackagingRequest {
     this.largeFile = flg;
    }
-    /**
-     \* {@inheritDoc}
-     */
-   @Override
-   public Map<String, String> getMetadata() {
-       return metadata;
-   }
  +
-    /**
-     \* {@inheritDoc}
-     */
-   @Override
-   public void setMetadata(Map<String,String> metadata) {
-       this.metadata = metadata;
-   }
  +
  }

**Comment by jthomaskerr** [comment]
Hmm...perhaps that was not a good way to submit a patch....there doesn't appear to be an attachment option...

**Comment by mepeisen** [comment]
Can you attach the patch as text file?

**Comment by jthomaskerr** [comment]
Here (hopefully) is the attachment.

On 8 June 2012 01:33, Martin Eisengardt <
reply@reply.github.com

**Comment by mepeisen** [comment]
hmmm. do not see any attachement. :(
So please add it to our trac: http://trac.php-maven.org/ticket/77
Or send it to me directly: martin.eisengardt@php-maven.org

Closing it know.
Please watch the trac ticket for news.
