### ISSUE TITLE
Fail to find 'phpdoc' under Linux

### ISSUE THREAD

**Issue by bgaillard** [php-maven/maven-php-plugin#2]
Hi, I'm currently using the maven-php-plugin to build our projects. 

I've encountered a problem in an Amazon EC2 Machine, it seems that the 'phpdoc' executable can't be found. 

This problem is encountered because the PhpDocumentor class get a PATH variable from "java.library.path" :

final String path = System.getProperty("java.library.path");

This is not correct because under UNIX PhpDocumentor can be installed in the '/usr/bin' directory. 

To fix the problem a user can pass the following arguments while doing a Maven install : 

mvn install -DphpDocFilePath=/usr/bin/phpdoc

This is only a workaround, to fix the problem the System.getProperty("java.library.path") must be replaced by an instruction used to read the System path. 

Sincerely, 

Baptiste

**Comment by mepeisen** [comment]
Hi.

Thats no clear. However the java.library.path is only requested for additional path. If the path was not overwritten and if the phpdoc executable is not found in java.library.path the operating system should be clever enough to find it (more in deep: the phpdoc command is passed to the os without any path info).

However the java.library.path is meant for dlls. So one could even pass paths for executables to it. The question is why your machine does not find it all by itself. Are you sure that the PATH variable is propert set? Did you test that for example a simple program finds the phpdoc executable?

**Comment by mepeisen** [comment]
Imported to trac. Will result in the test infrastrutre (CI servers for windows, ubuntu, suse and debian planned). Targeted for 2.0 release.

**Comment by mepeisen** [comment]
http://trac.php-maven.org/ticket/45
