### ISSUE TITLE
is this still active?

### ISSUE THREAD

**Issue by dmead** [php-maven/maven-php-plugin#22]
is this what i want to build php with maven? also, should this be down?

http://repos.php-maven.org/releases/org/phpmaven/php-parent-pom/2.0.2/php-parent-pom-2.0.2.pom

**Comment by edannenberg** [comment]
see  #20 ;/

has been inactive for a good while now and will probably stay this way

**Comment by dmead** [comment]
do you know of an alternative to getting a php project build in maven?

**Comment by giflw** [comment]
You can try use maven exec plugin to call php related tools like phing,
composer, etc, and use assembly plugin to build a zip/tar.gz archive for
distribution.
