### ISSUE TITLE
Update maven snapshot?

### ISSUE THREAD

**Issue by achingbrain** [php-maven/maven-php-plugin#4]
I have a file that defines more than one class which I am trying to unit test.  With the latest snapshot up at http://repos.xworlds.org/snapshots/org/phpmaven/maven-php-plugin/2.0-SNAPSHOT (11th November) the test phase fails with an error that it cannot work out which class I am trying to test.  However if I clone this repository and install the plugin manually, the test phase passes as expected.

Is there any plan to deploy an updated snapshot of maven-php-plugin to a public Maven repository?

**Comment by mepeisen** [comment]
Within the next days. Sry for the inactivity the last two months.

**Comment by mepeisen** [comment]
Just released a new one. Please retry it. If it does not work please send me some small project that reproduces the problem.

**Comment by mepeisen** [comment]
closed. If there are still problems please report them.

**Comment by achingbrain** [comment]
Sorry for my delay in replying - that appears to have solved the problem, thanks.
